#!/usr/bin/env python3
"""Splice src/*.lua into the single file WC3 actually executes.

The map script is one flat Lua namespace, so each module is wrapped in its own
`do ... end` block: locals stay private, `DND.*` stays shared. A leading
`local DND = nil` would break that, so we deliberately forbid it (the linter
already assumes a shared global namespace).

Usage: python3 tools/build.py [--out dist/war3map.lua]
"""
import pathlib
import re
import sys
import datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"

ORDER = [
    "dnd_const.lua",
    "dnd_rawcodes.lua",
    "dnd_w3.lua",
    "dnd_dice.lua",
    "dnd_combatant.lua",
    "dnd_turns.lua",
    "dnd_resolve.lua",
    "dnd_combat.lua",
    "dnd_ui.lua",
    "dnd_ai.lua",
    "dnd_data.lua",
    "dnd_input.lua",
]

BANNER = """--[[ ==========================================================================
   D&D in Warcraft III — turn-based combat engine
   GENERATED by tools/build.py from src/*.lua. Do not edit this file; edit the
   modules and rebuild.

   Modules: {modules}
========================================================================== ]]
"""


def main() -> int:
    out_path = ROOT / "dist" / "war3map.lua"
    if "--out" in sys.argv:
        out_path = pathlib.Path(sys.argv[sys.argv.index("--out") + 1])

    missing = [m for m in ORDER if not (SRC / m).exists()]
    extra = sorted(p.name for p in SRC.glob("*.lua")
                   if p.name not in ORDER and p.name != "war3map.lua")
    if missing:
        print(f"!! missing modules: {missing}")
        return 1
    if extra:
        print(f"!! modules not in build order (would be dropped): {extra}")
        return 1

    entry = (SRC / "war3map.lua").read_text(encoding="utf-8")
    body = [BANNER.format(modules=", ".join(ORDER))]
    body.append(f"-- built {datetime.date.today()} --\n")
    for name in ORDER:
        text = (SRC / name).read_text(encoding="utf-8")
        body.append(f"\n-- ------------------------------------------------------------ {name}\ndo\n")
        body.append(text)
        body.append("\nend\n")
    # splice the entry point between its markers so it stays editable in src
    head, _, tail = entry.partition("--<<BUILD:BEGIN>>--")
    _, _, tail = tail.partition("--<<BUILD:END>>--")
    body.append("\n-- ------------------------------------------------------------ bootstrap\n")
    body.append(head.split("--<<BUILD:END>>--")[-1] if "--<<BUILD:END>>--" in head else head)
    body.append("\ndo end\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    data = "".join(body)
    # the entry point's own top comment + markers are noise in the output
    data = data.replace("--<<BUILD:BEGIN>>--  (build.py splices the modules in here)\n", "")
    data = data.replace("--<<BUILD:END>>--\n", "")
    out_path.write_text(data, encoding="utf-8")

    lines = data.count("\n") + 1
    from luaparser import ast
    try:
        ast.parse(data)
    except Exception as exc:  # noqa: BLE001
        print(f"✗ dist file does not parse: {exc}")
        return 1
    print(f"wrote {out_path.relative_to(ROOT)}  ({lines} lines, {len(data)//1024} KiB) — parses OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
