#!/usr/bin/env python3
"""Emit `tools/dnd_data.js`: ObjectMerger blocks that create the real D&D object
data, so the map does not depend on stock Warcraft III units as stand-ins.

Why a generator: the numbers in src/dnd_data.lua are the rules' single source of
truth. Hand-typing them again into the Object Editor is how a map ends up with a
goblin that hits for 1d8 while the code says 1d6. This reads the statblocks and
writes the slk-level edits for you.

What it makes, per creature:
  * a unit   (hp, armour = AC-10, movement = speed, model)
  * actions that need no action economy (natural weapons, a cantrip attack) as
    real WC3 attacks with 1d0+0 damage — the engine rolls every number, the
    weapon exists only to give the model a swing animation and a threat range
  * every action as a hero ability, which is what the action bar and native
    right-click targeting (DND.config.nativeTargeting) drive

Usage: python3 tools/gen_data_js.py [--out tools/dnd_data.js]
"""
from __future__ import annotations
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

UNITS_PER_FOOT = 6.4
HP_SCALE = 4


def fourcc(code: str) -> int:
    n = 0
    for ch in code.encode("ascii"):
        n = (n << 8) | ch
    return n & 0xFFFFFFFF



UPF = 6.4          # units per foot
HP_SCALE = 4

# Read the statblocks by running the real Lua module, not by regex-parsing it.
# A hand-rolled parser on a language with `creature({ ... })` wrappers and nested
# tables will quietly invent creatures; the test harness already gives us a
# correct reader for free.
DUMP = r"""
EXPORT = {}
local out = {}
for key, spec in pairs(DND.Data.Bestiary) do
  local actions = {}
  for i, a in ipairs(spec.actions or {}) do
    actions[#actions+1] = {
      name = a.name or ("Action " .. i),
      reach = a.reach or (a.range and (a.range * 6.4)) or 32,
      dmgType = a.dmgType or "sludge",
      save = a.save or "", toHit = a.toHit or 0,
    }
  end
  out[#out+1] = {
    key = key, name = spec.name or key, model = spec.model or "hfoo",
    hp = spec.hp or 10, ac = spec.ac or 10, speed = spec.speed or 30,
    level = spec.level or 1, side = spec.side or 0,
    actions = actions,
  }
end
local parts = {}
for _, e in ipairs(out) do
  local acts = {}
  for _, a in ipairs(e.actions) do
    acts[#acts+1] = string.format("%s|%d|%s", a.name, math.floor(a.reach), a.dmgType)
  end
  parts[#parts+1] = string.format("%s;%s;%s;%d;%d;%d;%d;%s", e.key, e.name, e.model,
    e.hp, e.ac, e.speed, e.level, table.concat(acts, "~"))
end
table.sort(parts)
EXPORT = parts
"""


def read_bestiary() -> list[dict]:
    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    import harness
    lua = harness.boot()
    lua.execute(DUMP)
    raw = str(lua.execute("return table.concat(EXPORT, '\\n')"))
    out = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        key, name, model, hp, ac, speed, level, acts = line.split(";")
        actions = []
        for a in acts.split("~"):
            if not a:
                continue
            nm, reach, dtype = a.split("|")
            actions.append({"name": nm, "reach": int(reach), "type": dtype})
        out.append({"key": key, "name": name, "model": model, "hp": int(hp),
                    "ac": int(ac), "speed": int(speed), "level": int(level),
                    "actions": actions})
    return out


def ability_code(index: int) -> str:
    return f"A{index:03d}"


def unit_code(index: int) -> str:
    return f"u{index:03d}"


def main() -> int:
    bestiary = read_bestiary()
    if not bestiary:
        print("!! could not read Data.Bestiary (run the harness first)")
        return 1

    lines: list[str] = [
        "// GENERATED by tools/gen_data_js.py — do not hand-edit.",
        "// Paste into a JASS trigger (custom text) or run through",
        "// jassNewGenPack's ObjectMerger, then save and reopen the map.",
        "//",
        f"// {len(bestiary)} creatures. Each gets one unit and up to six abilities,",
        "// with 1d0+0 weapon damage on purpose: the Lua engine rolls every",
        "// number, so the model only needs a swing, a threat range and a bar.",
        "",
    ]
    ab = 0
    for e in bestiary:
        name = e["key"]
        ucode = unit_code(ab)
        display, base = e["name"], e["model"]
        hp, ac, speed, level = e["hp"], e["ac"], e["speed"], e["level"]
        ab += 1
        lines += [
            f"// ---- {display} ----",
            f"//! externalblock extension=lua ObjectMerger $FILENAME$",
            f"//! i   setobjecttype(\"units\")",
            f"//! i   createobject(\"{base}\", \"{ucode}\")",
            f"//! i   makechange(current, \"unam\", \"{display}\")",
            f"//! i   makechange(current, \"udes\", \"D&D level {level}. "
            f"AC {ac}, {hp} hp, speed {speed} ft. Stats live in dnd_data.lua.\")",
            f"//! i   makechange(current, \"uhpm\", {hp * HP_SCALE})",
            f"//! i   makechange(current, \"ud2a\", 0, {ac - 10})",
            f"//! i   makechange(current, \"umvs\", {round(speed * UPF / 6.0, 2)})",
            # no real damage: the swing is an animation, the dice are Lua's
            f"//! i   makechange(current, \"ua1b\", 0)",
            f"//! i   makechange(current, \"ua1d\", 0)",
            f"//! i   makechange(current, \"ua1s\", 0)",
            f"//! i   makechange(current, \"ua1c\", 99)",
            # reach on the model's own weapon: this is what makes a pike goblin
            # threaten 10 ft and an archer threaten 320 using nothing but WC3's
            # native attack range. 1d0+0 damage above means the engine's own
            # attack path can never leak real damage.
            (f"//! i   makechange(current, \"ua1r\", %d)"
             % max(a["reach"] for a in e["actions"])) if e["actions"] else "",
        ]
        codes = []
        for slot, act in enumerate(e["actions"][:6]):
            acode = ability_code(ab * 16 + slot)
            codes.append(acode)
            lines += [
                f"//! i   setobjecttype(\"abilities\")",
                f"//! i   createobject(\"Aamg\", \"{acode}\")",   # Aamg: the standard dummy-caster base
                f"//! i   makechange(current, \"anam\", \"{act['name']}\")",
                f"//! i   makechange(current, \"ahky\", \"123456\")",
                f"//! i   makechange(current, \"aart\", \"ReplaceableTextures\\\\CommandButtons\\\\BTNAttack.blp\")",
                f"//! i   makechange(current, \"Areq\", 1)",
                f"//! i   makechange(current, \"Acle\", 0)",
                f"//! i   makechange(current, \"Ahpr\", 1)",
            ]
        lines += [
            f"//! i   setobjecttype(\"units\")",
            f"//! i   makechange(current, \"uabi\", "
            + ", ".join(f'"{c}"' for c in codes) + ")" if codes else
            f"//! i   makechange(current, \"unam\", \"{display}\")",
            f"//! externalblock",
            "",
        ]

    lines += [
        "",
        "// ---- the shared shells every combatant needs ----",
        "//! externalblock extension=lua ObjectMerger $FILENAME$",
        "//! i   setobjecttype(\"abilities\")",
        "// AIDL: permanent locust so a frozen unit can never act on its own",
        "//! i   createobject(\"Aloc\", \"AIDL\")",
        "//! i   makechange(current, \"anam\", \"Waiting (turn-based)\")",
        "//! i   makechange(current, \"ahky\", \"\")",
        "// AMOV: the movement action; cast range is set per unit from its speed",
        "//! i   createobject(\"Avmg\", \"AMOV\")",
        "//! i   makechange(current, \"anam\", \"Move\")",
        "//! i   makechange(current, \"ahky\", \"T\")",
        "//! i   makechange(current, \"aart\", \"ReplaceableTextures\\\\CommandButtons\\\\BTNMoveTo.blp\")",
        "// AATK: the Strike action; range mirrors the creature's reach",
        "//! i   createobject(\"Aamg\", \"AATK\")",   # Aamg = Arrow/Missile/Generic
        "//! i   makechange(current, \"anam\", \"Attack\")",
        "//! i   makechange(current, \"ahky\", \"1\")",
        "//! i   makechange(current, \"aart\", \"ReplaceableTextures\\\\CommandButtons\\\\BTNAttack.blp\")",
        "//! i   makechange(current, \"Areq\", 1)",
        "//! i   makechange(current, \"Acdn\", 0)",
        "//! externalblock",
        "",
    ]
    out = pathlib.Path(sys.argv[sys.argv.index("--out") + 1]) if "--out" in sys.argv \
        else ROOT / "tools" / "dnd_data.js"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(lines)} lines, {len(bestiary)} creatures)")
    print("rawcodes used: " + ", ".join(f"{k}={v:08X}" for k, v in
          {"AIDL": fourcc("AIDL"), "AMOV": fourcc("AMOV"), "AATK": fourcc("AATK")}.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
