#!/usr/bin/env python3
"""Emit verified four-char-code -> integer constants for the Lua side.

WC3's Lua has no guaranteed FourCC(), so every rawcode the engine touches is
precomputed here and baked into src/dnd_rawcodes.lua.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def fourcc(code: str) -> int:
    assert len(code) == 4, code
    n = 0
    for ch in code.encode("ascii"):
        n = (n << 8) | ch
    return n & 0xFFFFFFFF


def hx(n: int) -> str:
    return f"0x{n:08X}"


CODES = {
    # --- generated ability rawcodes (must match dnd_data.js) ---
    "MOVE": "AMOV", "ATTACK": "AATK", "DASH": "ADSH", "DISENGAGE": "ADSG",
    "DODGE": "ADDG", "HELP": "AHL0", "STABILIZE": "ASTB", "BONUS_ATK": "ABNA",
    "IDLE": "AIDL",
    "SPELL": "AS00", "TRAIT": "ATR0", "ITEM": "AIT0",
    # --- vanilla abilities we clone / borrow ---
    "LOCUST": "Aloc", "CHANNEL": "Achl", "SMART": "Avmg", "CROP": "Avcg",
    "ANTIMAGIC": "Amal", "SLOW": "Aslo", "THORNS": "Atho", "HOLYBOL": "AHhb",
    # --- vanilla unit rawcodes used as object-editor bases ---
    "U_FOOTMAN": "hfoo", "U_GRUNT": "ogru", "U_KNIGHT": "hkni",
    "U_WITCH": "Hbal", "U_MAGE": "Hblm", "U_ROGUE": "Harb",
    "U_SHAMAN": "Oshm", "U_BEAST": "Utst", "U_DRAGON": "Hadr",
    "U_STALKER": "Eutm", "U_GOLEM": "Ngma", "U_DUMMY": "ueat",
    # --- orders (orderIds from common.j) ---
    "ORDER_MOVE": "pointmove", "ORDER_ATTACK": "attack", "ORDER_STOP": "stop",
}

ORDER_IDS = {"pointmove": 0x00000001, "attack": 0x00000002, "stop": 0x00000003}

LINES = [
    "--[[ =========================================================================",
    "  dnd_rawcodes.lua -- GENERATED by tools/gen_rawcodes.py. Do not hand-edit.",
    "",
    "  WC3's Lua has no reliable FourCC(), so every four-char code the engine",
    "  touches is precomputed. Field codes are also listed so the object-data",
    "  generator and the runtime both speak the same table.",
    "========================================================================== ]]",
    "DND = DND or {}",
    "DND.RC = {}",
    "local R = DND.RC",
    "",
    "-- object-editor rawcodes (ability / unit ids)",
]
for name, code in CODES.items():
    if code in ORDER_IDS:
        continue
    LINES.append(f"R.{name} = {hx(fourcc(code))}   -- '{code}'")

LINES += ["", "-- spell slots AS00..AS08 and traits ATR0..ATR7 are offsets",
          "R.SPELL_COUNT = 9", "R.TRAIT_COUNT = 8", "R.ITEM_COUNT = 6", "",
          "-- issued-order ids (orderIds, see common.j)",
          ]
for name, code in ORDER_IDS.items():
    LINES.append(f"R.ORDER_{name.upper()} = {hx(code)}")

LINES += ["", "-- object-editor field slks (what dnd_data.js writes)",
          "-- unit fields"]
UNIT_FIELDS = {
    "NAME": "unam", "LEVEL": "udur", "HP": "uhpm", "HP_BASE": "uhb1",
    "MANA": "umpm", "ARMOR": "udf1", "DEFENSE": "ud2a", "MOVEMENT": "umvs",
    "VISION": "ubsb", "DAY_SIGHT": "usum", "TURN_RATE": "utrn",
    "ACQ_RANGE": "uacr", "COLLISION": "ucbs", "SCALE": "uscl",
    "TYPE": "utyp", "CATEGORY": "ucat", "PATROL": "upat",
    "STR": "ustm", "AGI": "uagm", "INT": "uint", "STR_BONUS": "ustb",
    "DICE_NUMBER": "ua1d", "DICE_SIDES": "ua1s", "DAMAGE_BASE": "ua1b",
    "ATTACK_TYPE": "ua1t", "ATTACK_RANGE": "ua1r", "ATTACK_COOLDOWN": "ua1c",
    "DAMAGE_POINT": "udp1", "ATTACK_ENABLED": "uaen", "WEAPON_ART": "ua1e",
    "ATTACK_ART": "ua1m", "REPLY_ART": "uaar", "DEATH_ART": "Utdt",
    "DEATH_TYPE": "udde", "FLOAT_TEXT": "uft1", "CAN_FLY": "umvt",
    "HUMAN_DESC": "udes", "GOLD": "ugol",
}
for k, v in sorted(UNIT_FIELDS.items()):
    LINES.append(f"R.UNIT_{k} = {hx(fourcc(v))}   -- '{v}'")

LINES += ["", "-- ability fields"]
# Only slks we actually rely on at runtime; everything else is set in the
# Object Editor by dnd_data.js and never read back from Lua.
ABIL_FIELDS = {
    "NAME": "anam", "ART": "aart", "DATA_A": "data",
    "COOLDOWN": "Acdn", "NORMAL_CD": "Anrm", "HERO_CD": "Ahri",
    "REQ_TARGET": "areq", "ART_TARGET": "Atar", "ART_CAST": "Atac",
    "BUFF_NAME": "abuf", "HOTKEY": "ahun", "LEVELS": "alev",
}
for k, v in sorted(ABIL_FIELDS.items()):
    LINES.append(f"R.ABIL_{k} = {hx(fourcc(v))}   -- '{v}'")

LINES += ["", "return R", ""]
(ROOT / "src" / "dnd_rawcodes.lua").write_text("\n".join(LINES), encoding="utf-8")
print(f"wrote src/dnd_rawcodes.lua ({len(LINES)} lines)")
