#!/usr/bin/env python3
"""Regenerate tools/ref/api_names.txt — the name list the natives gate reads.

`tools/lint_natives.py` refuses to run unless it can check every global call in `src/*.lua`
against a real WC3 API. The full JASS headers are ~820 KB of Blizzard scripting data, so they
are not committed; what the gate actually needs is the *set of declared names*, and that is
what this file produces (a few hundred KB of JASS becomes ~30 KB of identifiers).

Where the headers come from — the wc3-ts-declarations project keeps a verbatim copy of the
engine's `common.j` and `Blizzard.j`:

    https://raw.githubusercontent.com/wc3ts/wc3-ts-declarations/master/jass-api/common.j
    https://raw.githubusercontent.com/wc3ts/wc3-ts-declarations/master/jass-api/Blizzard.j

(Note the branch is `master`; `/main/` 404s. If you are reading this after a WC3 patch, that
is also the file to re-fetch: a native added in a patch should stop being an error here.)

Usage:
    python3 tools/gen_ref.py                 # from tools/ref/common.j + Blizzard.j
    python3 tools/gen_ref.py --fetch         # download them first, then generate
"""
from __future__ import annotations

import pathlib
import re
import sys
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
REF = HERE / "ref"
OUT = REF / "api_names.txt"
SOURCES = {
    "common.j": "https://raw.githubusercontent.com/wc3ts/wc3-ts-declarations/master/jass-api/common.j",
    "Blizzard.j": "https://raw.githubusercontent.com/wc3ts/wc3-ts-declarations/master/jass-api/Blizzard.j",
}

# The four declaration forms that create a global name callable from Lua. Nothing else in
# JASS does, which is the whole reason this list is enough for the gate.
PATTERNS = [
    r"^\s*native\s+(\w+)",
    r"^\s*constant\s+native\s+(\w+)",
    r"^\s*constant\s+\w+\s+(\w+)",
    r"^\s*(?:public\s+|private\s+)?function\s+(\w+)",
]


def names_from(text: str) -> set[str]:
    out: set[str] = set()
    for pat in PATTERNS:
        out |= set(re.findall(pat, text, re.M))
    return out


def main() -> int:
    if "--fetch" in sys.argv:
        REF.mkdir(parents=True, exist_ok=True)
        for fname, url in SOURCES.items():
            dest = REF / fname
            print(f"fetching {fname} ...")
            dest.write_bytes(urllib.request.urlopen(url, timeout=60).read())
            print(f"  wrote {dest} ({dest.stat().st_size // 1024} KiB)")

    found = [p for p in (REF / "common.j", REF / "Blizzard.j") if p.exists()]
    if not found:
        print("no tools/ref/common.j or Blizzard.j — run:  python3 tools/gen_ref.py --fetch")
        return 2

    names: set[str] = set()
    for p in found:
        got = names_from(p.read_text(encoding="utf-8", errors="replace"))
        print(f"  {p.name}: {len(got)} declared names")
        names |= got

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(sorted(names))
    OUT.write_text(
        "# Generated by tools/gen_ref.py — do not edit.\n"
        "# Every global name a WC3 Lua script may call: natives, native constants and\n"
        "# functions declared in common.j / Blizzard.j. Regenerate after a game patch, or\n"
        "# after fetching newer headers (see gen_ref.py's docstring for the URLs).\n"
        f"# {len(names)} names from: {', '.join(p.name for p in found)}\n"
        + body + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(HERE.parent)}  ({len(names)} names, "
          f"{OUT.stat().st_size // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
