#!/usr/bin/env python3
"""Gate: every global the engine calls must be a real WC3 native, a
Blizzard.j function, a project symbol, or a Lua 5.1 builtin.

WC3 maps have no module system, no linker, no type checker, and no debugger
worth the name. A typo'd native is `nil` at runtime and only explodes when the
player happens to press that button — so we resolve every called name here
instead. war3map.lua is included on purpose: entry-point-only natives (player
slot state, map extents) would otherwise be the one blind spot.

Usage: python3 tools/lint_natives.py [--verbose]
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
HERE = pathlib.Path(__file__).resolve().parent
# The gate reads the API out of `tools/ref/`, in this order: the real JASS headers if they
# are in the tree (820 KB of Blizzard data, not committed), else `api_names.txt` beside
# them — the same set of declared names, generated by `tools/gen_ref.py`, which is what a
# fresh clone has. Nothing outside the repo is consulted: a stray /tmp/common.j from a
# scratch session silently swapping the reference under a gate is how a gate starts
# passing things that should fail.
J_FILES = [HERE / "ref" / "common.j", HERE / "ref" / "Blizzard.j"]
API_TXT = HERE / "ref" / "api_names.txt"

# Lua 5.1 builtins plus what WC3 injects into the environment.
BUILTINS = set("""
assert error pcall xpcall type tostring tonumber pairs ipairs next rawget rawset rawequal
setmetatable getmetatable select unpack table string math os io print require dofile
loadstring load format insert remove concat sort rep find sub len byte char gmatch match
floor ceil abs max min fmod modf sqrt random seed atan2 huge pi deg rad
""".split())

KEYWORDS = set("""
local function and or not then do end if else elseif return while repeat until for in
break nil true false goto self
""".split())


def strip_noise(text: str) -> str:
    text = re.sub(r"--\[\[.*?\]\]", "", text, flags=re.S)
    text = re.sub(r"--[^\n]*", "", text)
    text = re.sub(r"\[=+\[.*?\]=+\]", "", text, flags=re.S)
    text = re.sub(r'"(?:\\.|[^"\\\n])*"', '""', text)
    text = re.sub(r"'(?:\\.|[^'\\\n])*'", "''", text)
    return text


def locals_of(text: str) -> set[str]:
    out: set[str] = set()
    for chunk in re.findall(r"\blocal\s+([A-Za-z_][\w,\s=]*)", text):
        out |= set(re.findall(r"[A-Za-z_]\w*", chunk))
    for chunk in re.findall(r"\bfor\s+([A-Za-z_][\w,\s]*)\s+(?:in|=)", text):
        out |= set(re.findall(r"[A-Za-z_]\w*", chunk))
    for chunk in re.findall(r"\bfunction\s+[\w.:]*\(([^)]*)\)", text):
        out |= set(re.findall(r"[A-Za-z_]\w*", chunk))
    return out


def main() -> int:
    verbose = "--verbose" in sys.argv
    files = sorted(p for p in (ROOT / "src").glob("*.lua"))
    if not files:
        print("no src/*.lua")
        return 2

    allow = set(BUILTINS) | set(KEYWORDS)
    api_from = ""
    present = J_FILES if all(p.exists() for p in J_FILES) else []
    if present:
        for p in present:
            t = p.read_text(encoding="utf-8", errors="replace")
            allow |= set(re.findall(r"^\s*native\s+(\w+)", t, re.M))
            allow |= set(re.findall(r"^\s*constant\s+\w+\s+(\w+)", t, re.M))
            allow |= set(re.findall(r"^\s*constant\s+native\s+(\w+)", t, re.M))
            allow |= set(re.findall(r"^\s*(?:public\s+|private\s+)?function\s+(\w+)", t, re.M))
        api_from = ", ".join(p.name for p in present)
    elif API_TXT.exists():
        allow |= {ln.strip() for ln in API_TXT.read_text(encoding="utf-8").splitlines()
                  if ln and not ln.startswith("#")}
        api_from = API_TXT.relative_to(ROOT).as_posix()
    else:
        print("!! no WC3 API reference: fetch the headers and run tools/gen_ref.py "
              "(see its docstring for the URLs) — a gate that silently allows "
              "everything is worse than no gate")
        return 2

    # everything the project itself defines, in any file, entry point included
    raw = {f: f.read_text(encoding="utf-8") for f in files}
    stripped = {f: strip_noise(t) for f, t in raw.items()}
    all_raw = "\n".join(raw.values())
    allow |= {"DND"}
    allow |= set(re.findall(r"^DND\.(\w+)", all_raw, re.M))
    allow |= {f"DND.{x}" for x in re.findall(r"^DND\.(\w+)", all_raw, re.M)}
    allow |= set(re.findall(r"^function\s+([A-Za-z_][\w.]*)", all_raw, re.M))
    allow |= {m.split(".")[0] for m in re.findall(r"^function\s+([A-Za-z_][\w.]*)", all_raw, re.M)}
    allow |= set(re.findall(r"^local\s+function\s+(\w+)", all_raw, re.M))
    allow |= set(re.findall(r"^(?:local\s+)?(\w+)\s*=\s*\{", all_raw, re.M))
    for t in stripped.values():
        allow |= locals_of(t)

    called: dict[str, set[str]] = {}
    for f, t in stripped.items():
        for name in re.findall(r"(?<![.:\w])([A-Za-z_]\w*)\s*[\(\[]", t):
            called.setdefault(name, set()).add(f.name)

    unknown = {k: v for k, v in called.items() if k not in allow}
    if unknown:
        print(f"{len(unknown)} unrecognised call(s):")
        for name in sorted(unknown):
            print(f"  {name:34s} <- {','.join(sorted(unknown[name]))}")
        return 1
    if verbose:
        print(f"OK — {len(called)} called names all resolve to a native, "
              f"Blizzard.j, a Lua builtin, or project code")
    else:
        print(f"OK — every called name resolves to a native, Blizzard.j, or project code"
              f"  [api: {api_from}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
