--[[ =========================================================================
  dnd_rawcodes.lua -- GENERATED by tools/gen_rawcodes.py. Do not hand-edit.

  WC3's Lua has no reliable FourCC(), so every four-char code the engine
  touches is precomputed. Field codes are also listed so the object-data
  generator and the runtime both speak the same table.
========================================================================== ]]
DND = DND or {}
DND.RC = {}
local R = DND.RC

-- object-editor rawcodes (ability / unit ids)
R.MOVE = 0x414D4F56   -- 'AMOV'
R.ATTACK = 0x4141544B   -- 'AATK'
R.DASH = 0x41445348   -- 'ADSH'
R.DISENGAGE = 0x41445347   -- 'ADSG'
R.DODGE = 0x41444447   -- 'ADDG'
R.HELP = 0x41484C30   -- 'AHL0'
R.STABILIZE = 0x41535442   -- 'ASTB'
R.BONUS_ATK = 0x41424E41   -- 'ABNA'
R.IDLE = 0x4149444C   -- 'AIDL'
R.SPELL = 0x41533030   -- 'AS00'
R.TRAIT = 0x41545230   -- 'ATR0'
R.ITEM = 0x41495430   -- 'AIT0'
R.LOCUST = 0x416C6F63   -- 'Aloc'
R.CHANNEL = 0x4163686C   -- 'Achl'
R.SMART = 0x41766D67   -- 'Avmg'
R.CROP = 0x41766367   -- 'Avcg'
R.ANTIMAGIC = 0x416D616C   -- 'Amal'
R.SLOW = 0x41736C6F   -- 'Aslo'
R.THORNS = 0x4174686F   -- 'Atho'
R.HOLYBOL = 0x41486862   -- 'AHhb'
R.U_FOOTMAN = 0x68666F6F   -- 'hfoo'
R.U_GRUNT = 0x6F677275   -- 'ogru'
R.U_KNIGHT = 0x686B6E69   -- 'hkni'
R.U_WITCH = 0x4862616C   -- 'Hbal'
R.U_MAGE = 0x48626C6D   -- 'Hblm'
R.U_ROGUE = 0x48617262   -- 'Harb'
R.U_SHAMAN = 0x4F73686D   -- 'Oshm'
R.U_BEAST = 0x55747374   -- 'Utst'
R.U_DRAGON = 0x48616472   -- 'Hadr'
R.U_STALKER = 0x4575746D   -- 'Eutm'
R.U_GOLEM = 0x4E676D61   -- 'Ngma'
R.U_DUMMY = 0x75656174   -- 'ueat'

-- spell slots AS00..AS08 and traits ATR0..ATR7 are offsets
R.SPELL_COUNT = 9
R.TRAIT_COUNT = 8
R.ITEM_COUNT = 6

-- issued-order ids (orderIds, see common.j)
R.ORDER_POINTMOVE = 0x00000001
R.ORDER_ATTACK = 0x00000002
R.ORDER_STOP = 0x00000003

-- object-editor field slks (what dnd_data.js writes)
-- unit fields
R.UNIT_ACQ_RANGE = 0x75616372   -- 'uacr'
R.UNIT_AGI = 0x7561676D   -- 'uagm'
R.UNIT_ARMOR = 0x75646631   -- 'udf1'
R.UNIT_ATTACK_ART = 0x7561316D   -- 'ua1m'
R.UNIT_ATTACK_COOLDOWN = 0x75613163   -- 'ua1c'
R.UNIT_ATTACK_ENABLED = 0x7561656E   -- 'uaen'
R.UNIT_ATTACK_RANGE = 0x75613172   -- 'ua1r'
R.UNIT_ATTACK_TYPE = 0x75613174   -- 'ua1t'
R.UNIT_CAN_FLY = 0x756D7674   -- 'umvt'
R.UNIT_CATEGORY = 0x75636174   -- 'ucat'
R.UNIT_COLLISION = 0x75636273   -- 'ucbs'
R.UNIT_DAMAGE_BASE = 0x75613162   -- 'ua1b'
R.UNIT_DAMAGE_POINT = 0x75647031   -- 'udp1'
R.UNIT_DAY_SIGHT = 0x7573756D   -- 'usum'
R.UNIT_DEATH_ART = 0x55746474   -- 'Utdt'
R.UNIT_DEATH_TYPE = 0x75646465   -- 'udde'
R.UNIT_DEFENSE = 0x75643261   -- 'ud2a'
R.UNIT_DICE_NUMBER = 0x75613164   -- 'ua1d'
R.UNIT_DICE_SIDES = 0x75613173   -- 'ua1s'
R.UNIT_FLOAT_TEXT = 0x75667431   -- 'uft1'
R.UNIT_GOLD = 0x75676F6C   -- 'ugol'
R.UNIT_HP = 0x7568706D   -- 'uhpm'
R.UNIT_HP_BASE = 0x75686231   -- 'uhb1'
R.UNIT_HUMAN_DESC = 0x75646573   -- 'udes'
R.UNIT_INT = 0x75696E74   -- 'uint'
R.UNIT_LEVEL = 0x75647572   -- 'udur'
R.UNIT_MANA = 0x756D706D   -- 'umpm'
R.UNIT_MOVEMENT = 0x756D7673   -- 'umvs'
R.UNIT_NAME = 0x756E616D   -- 'unam'
R.UNIT_PATROL = 0x75706174   -- 'upat'
R.UNIT_REPLY_ART = 0x75616172   -- 'uaar'
R.UNIT_SCALE = 0x7573636C   -- 'uscl'
R.UNIT_STR = 0x7573746D   -- 'ustm'
R.UNIT_STR_BONUS = 0x75737462   -- 'ustb'
R.UNIT_TURN_RATE = 0x7574726E   -- 'utrn'
R.UNIT_TYPE = 0x75747970   -- 'utyp'
R.UNIT_VISION = 0x75627362   -- 'ubsb'
R.UNIT_WEAPON_ART = 0x75613165   -- 'ua1e'

-- ability fields
R.ABIL_ART = 0x61617274   -- 'aart'
R.ABIL_ART_CAST = 0x41746163   -- 'Atac'
R.ABIL_ART_TARGET = 0x41746172   -- 'Atar'
R.ABIL_BUFF_NAME = 0x61627566   -- 'abuf'
R.ABIL_COOLDOWN = 0x4163646E   -- 'Acdn'
R.ABIL_DATA_A = 0x64617461   -- 'data'
R.ABIL_HERO_CD = 0x41687269   -- 'Ahri'
R.ABIL_HOTKEY = 0x6168756E   -- 'ahun'
R.ABIL_LEVELS = 0x616C6576   -- 'alev'
R.ABIL_NAME = 0x616E616D   -- 'anam'
R.ABIL_NORMAL_CD = 0x416E726D   -- 'Anrm'
R.ABIL_REQ_TARGET = 0x61726571   -- 'areq'

return R
